### PR TITLE
Flatbuffer Struct Padding issue

### LINKED ISSUE #52: Extra Padding issue on extra accounts.
A bug was shipped in the status instruction that pulls the first 32 bytes from the flatbuffers account struct.
 The bug was also featured in the node to do the same thing which allows the pubkey to incorrectly match and not error, but this added a weird byte offset that causes the pubkey to be wrong, but as stated it did not fail the on chain checks since it is doing the same thing.

Example Culprit Code
``` 
let (pkbytes, writable) = a.0.split_at(32);
let pubkey = Pubkey::try_from(pkbytes).unwrap_or_default();
AccountMeta {
    pubkey,
    is_writable: writable[0] == 1,
    is_signer: false,
}
```
Flat buffer schema
```
struct Account {
  writable: bool = false;
  pubkey: [uint8:32];
}
```
Since this is a struct, the byte layout is much simpler as opposed to a table, which means it looks like more like a 33 byte slice. 
We are grabbing the pubkey from the wrong offset 0 instead of 1.

Instead we should be using the methods to pull these fields.

### PR DESCRIPTION
**Pull request by austbot**
- Resolves #52 
- Upgrades flatbuffers (note user needs to upgrade flatc)

 Note this is a breaking change for current contract users as now with the forces 8 byte alignment account is now 40 bytes not 33. This means, its aligned so its faster, but it means that once deployed, prover nodes must expect 40 bytes or there will be errors. 
At this stage Im certain we can communicate the change, and have no breakage as additional callback accounts greater than the first one will have been wrong.  SInce we are pre 1.0 I think this is fine. But I see that we could use this opportunity to test out the versioning process. for the flat buffer structs.

### CODE REVIEW

File: schemas-ts/dist/account.d.ts [hunk 1]
```diff
@@ -3,17 +3,17 @@ export declare class Account implements flatbuffers.IUnpackableObject<AccountT>
     bb: flatbuffers.ByteBuffer | null;
```
Comment (jac18281828) [inline schemas-ts/dist/account.d.ts:3]: I don't think dist/ is supposed to be checked in?

Comment (jac18281828) [reply schemas-ts/dist/account.d.ts:3]: I understand this may be out of scope

**Review by jac18281828 — APPROVED** [review]
We may consider deleting the dist/ hierarchy from javascript in an upcoming commit.

Overall this looks good and is passing basic checks.

Thanks! ⛏️

File: schemas-ts/dist/account.d.ts (hunk 1 above)
Comment (austbot) [reply schemas-ts/dist/account.d.ts:3]: yeah i should delete will do when new sdk arrives
