### PR TITLE
fix: Add optional S3 endpoint to upload arguments

### LINKED ISSUE #108: Error deploying bonsol manifest.json with Cloudflare R2: Binary mismatch issue
## Description  
I am attempting to deploy a `bonsol` `manifest.json` using Cloudflare R2 as the S3-compatible storage. The bucket region and URL settings are configured correctly. However, I encountered the following error during deployment:  

P.S. also happen when using iDrive e2 

### Steps to Reproduce  

1. Set up an S3-compatible bucket on Cloudflare R2. (follow this guide https://developers.cloudflare.com/r2/api/s3/api/#bucket-region)
   - **Bucket Name:** `bonsol202412`  
   - **Region:** `us-east-1`
   - **URL:** `https://***.r2.cloudflarestorage.com/bonsol202412`  
2. Run the following deployment command:  
   ```bash  
   bonsol deploy -m ./ikkyuz/manifest.json -t url --url https://***.r2.cloudflarestorage.com/bonsol202412 --region us-east-1 --bucket bonsol202412 --access-key *** --secret-key *** --storage-account s3://bonsol202412  
   ```  

## Error Message  

```plaintext  
Error: The binary uploaded does not match the local binary at path './ikkyuz/target/riscv-guest/riscv32im-risc0-zkvm-elf/docker/ikkyuz/ikkyuz', is the URL correct?  
upload_url: https://***.r2.cloudflarestorage.com/bonsol202412  
```  

## Expected Behavior  
The manifest and binary should be successfully uploaded to the specified bucket on Cloudflare R2 without mismatch errors.  

#### Actual Behavior  
The deployment fails with an error stating that the binary uploaded does not match the local binary.  

## Environment  

- **OS:** macOS 15.1.1
- **Bonsol Version:** v0.2.1

## Additional Information  
- I have verified that the bucket URL and region are correct.  
- The error suggests a binary mismatch between the local file and the uploaded binary.  

Would appreciate any guidance or fixes for this issue!

### PR DESCRIPTION
**Pull request by kidneyweakx**
### Description  
Add an optional `endpoint` field in the `S3UploadArgs` struct. Users can now specify a custom AWS S3-compatible endpoint, enhancing the deployment function's flexibility for working with different S3-compatible services.  

The changes include:  
1. Modifying the `S3UploadArgs` struct to include an `endpoint` field.  
2. Updating the deployment logic to use the provided `endpoint` if specified.  
3. Defaulting to the standard S3 URL format when the `endpoint` field is not provided.  
4. Updating the `AmazonS3Builder` configuration to incorporate the custom endpoint.

---

### Testing  
- **Case 1: Without `endpoint` field**  
  Input:  
  ```bash
    bonsol deploy --deploy-type <DEPLOY_TYPE> --bucket <BUCKET> --access-key <ACCESS_KEY> --secret-key <SECRET_KEY> --region <REGION> --url <URL> --manifest-path <MANIFEST_PATH> <--create|--storage-account <STORAGE_ACCOUNT>>
  ```  
  Expected: URL defaults to `https://example-bucket.s3.us-west-1.amazonaws.com/...`.  

- **Case 2: With `endpoint` field**  
  Input:  
  ```bash
   bonsol deploy --deploy-type <DEPLOY_TYPE> --bucket <BUCKET> --access-key <ACCESS_KEY> --secret-key <SECRET_KEY> --region <REGION> --url <URL> --manifest-path <MANIFEST_PATH> <--create|--storage-account <STORAGE_ACCOUNT>> --endpoint https://custom-s3-endpoint.com/...
  ```  
  Expected: URL uses the custom endpoint `https://custom-s3-endpoint.com/...`.  

---

### Checklist  
- [x] Added `endpoint` field to `S3UploadArgs`.  
- [x] Updated `AmazonS3Builder` logic for custom endpoint.  
- [x] Tested with and without the `endpoint` field.  

---

### Related Issues  
- Resolves #108 

### References
- https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.with_endpoint

### CODE REVIEW

File: cli/src/deploy.rs [hunk 1]
```diff
@@ -53,14 +53,25 @@ pub async fn deploy(rpc_url: String, signer: Keypair, deploy_args: DeployArgs) -
...
                 region,
+                endpoint,
                 ..
             } = s3_upload;
 
+            let dest =
+            object_store::path::Path::from(format!("{}-{}", manifest.name, manifest.image_id));
+
+            let url = if let Some(endpoint) = endpoint {
+                format!("{}", endpoint)
```
Comment (eureka-cpu) [inline cli/src/deploy.rs:64]: Since `endpoint` is already a `String` here I believe you can just return that instead of creating a new `String` with the `format!` macro

Comment (eureka-cpu) [reply cli/src/deploy.rs:64]: For even more style points you could try (didn't test it but should be close):
```rust
let url = endpoint.unwrap_or(format!("https://{}.s3.{}.amazonaws.com/{}", bucket, region, dest));
```

Comment (kidneyweakx) [reply cli/src/deploy.rs]: Good catch! I’ve updated the code to return the existing endpoint directly instead of using format!. Thanks for pointing it out!

**Review by eureka-cpu — APPROVED** [review]
Thanks again for this @kidneyweakx 🙂
